### ISSUE TITLE
Allow not setting policy page

### ISSUE THREAD

**Issue by XhmikosR** [progcode/WPCookieConsent#1]
Hi.

Thanks for the plugin. I'm gonna start using it in my projects.

One thing I notice compared to the latest JS version is that you don't allow not setting a policy page. Since it can be time consuming, I'm trying to add the dialog at first so I'd like to ask if you could add an option to skip the page.

**Comment by progcode** [comment]
Hi,

Thanks, this is now fixed in 1.0.3 version. You can upgrade your plugin from WordPress admin.

Cheers,
Daniel

**Comment by XhmikosR** [comment]
Cheers, thanks, I'll try it tomorrow.
