### ISSUE TITLE
Include styles using WP API

### ISSUE THREAD

**Issue by XhmikosR** [progcode/WPCookieConsent#2]
The way the styles are loaded require yet another HTTP request.

Would it be possible to enqueue the style instead of loading it via JS?

**Comment by progcode** [comment]
Hi,

sorry, but this is not an bug. The original silktide plugin working is same way. I marked this issue with "enhancement" label, so I will develop this feature soon.

Cheers,
Daniel

**Comment by progcode** [comment]
This feature is now available in v1.0.5 - https://github.com/progcode/WPCookieConsent/releases
