### ISSUE TITLE
Missing brace in dark-floating.css

### ISSUE THREAD

**Issue by ecksite** [progcode/WPCookieConsent#9]
There is one brace missing in dark-floating.css:

Please add a brace after the following code, since the mobile view is corrupted when using this style (no background etc).

```
@media screen and (min-width: 500px) {
    .cc_container {
        left: initial;
        right: 20px;
        bottom: 20px;
        width: 300px;
        padding-bottom: 77px
    }

    .cc_container .cc_btn {
        right: 15px;
        bottom: 37px
    }
```

Btw: It's not good practice to manually exclude semi-colons. I would recomment, adding semicolons in your css files...

**Comment by progcode** [comment]
UNMAINTAINED.
